# Generated by Django 4.2.7 on 2023-11-06 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0002_profile_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='email',
        ),
    ]
