# Generated by Django 4.2.7 on 2023-11-09 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0006_history_profile_history'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='is_sad',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='time_stamp',
        ),
    ]
