# Generated by Django 4.2.7 on 2023-11-09 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0008_remove_profile_first_name_remove_profile_last_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='phone',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
